project:
  type: website
  output-dir: ../public/_site

website:
  title: "Quarto"
  navbar:
    left:
      - href: index.qmd
      - text: RNA seq
        menu:
          - deseq2/inicio.qmd
          - deseq2/example.qmd

format:
  html:
    theme: journal
    css: styles.css
    toc: true
    number-sections: true
    embed-resources: true



