project:
  type: website
  output-dir: ../public/_site

website:
  search: false
  navbar:
    left:
      - text: Home  
        href: ../index.html
      - text: RNA seq
        menu:
          - deseq2/inicio.qmd
          - deseq2/example.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    number-sections: true
    embed-resources: true



